# configuration for the database
# Do not commit changes to this file unless it is for new configuration properties.
databaseConfig:
  host: sqlserver
  instance: SQLEXPRESS
  port: ${SQL_PORT}

# Database Generation configuration
# Order of operations: Create DBs (with schemas), Create Users (with schemas), Create Logins (to databases)
genConfig:
  # database project is setup as a git submodule
  # to get for the first time: git submodule update --init --recursive
  # to pull updates: git submodule update --recursive --remote
  schemaDir: ./OpenKO-db
  gameDb:
    - name: ${GAME_DB_NAME}
      # Forbid options are here if you want to prevent a database from processing an operation type
      # this can be useful if you want to have a source database to export from, and a test database to import to
      isForbidClean: false
      isForbidImport: false
      isForbidExport: true
      schemas:
        - ${GAME_DB_SCHEMA}
      # logins are stored under db config as a way of specifying their default database;
      # the same login should not be specified for multiple dbs
      logins:
        - name: ${GAME_DB_USER}
          pass: ${GAME_DB_PASS}
      # we're creating users at the database-level to discourage the use of system database users
      # it should be OK to create the same user in multiple non-system databases if you want to
      # reuse the same user
      users:
        - name: ${GAME_DB_USER}
          schema: ${GAME_DB_SCHEMA}
