# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Build all (MSBuild)"

on:
  push:
    branches:
    - master

    # This specifically builds when anything relating to a build changes.
    # Everything else can be ignored.
    paths:
      - '.github/workflows/build_msbuild_all.yml'
      - '**/*.props'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.vcxproj'
      - 'deps/**'
      - 'All.sln'
      - 'ThirdParty.sln'

  pull_request:
    branches:
    - master

    # This specifically builds when anything relating to a build changes.
    # Everything else can be ignored.
    paths:
      - '.github/workflows/build_msbuild_all.yml'
      - '**/*.props'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.vcxproj'
      - 'deps/**'
      - 'All.sln'
      - 'ThirdParty.sln'

  merge_group: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]
        BUILD_PLATFORM: [Win32]

    name: "All: ${{ matrix.BUILD_CONFIGURATION }} - ${{ matrix.BUILD_PLATFORM }}"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Clone OpenKO-runner-dependencies
      run: git clone https://github.com/Open-KO/OpenKO-runner-dependencies --depth 1

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    # NOTE: We could simply run All.sln, but it makes it far more obvious in the Github output when it's broken up across its solutions.
    - name: Build third party dependencies
      run: msbuild /p:Configuration="${{matrix.BUILD_CONFIGURATION}}" /p:Platform="${{matrix.BUILD_PLATFORM}}" /p:NO_CLIENT_ASSETS="1" ThirdParty.sln

    - name: Build client
      run: msbuild /p:Configuration="${{matrix.BUILD_CONFIGURATION}}" /p:Platform="${{matrix.BUILD_PLATFORM}}" /p:NO_CLIENT_ASSETS="1" Client.sln

    - name: Build server
      run: msbuild /p:Configuration="${{matrix.BUILD_CONFIGURATION}}" /p:Platform="${{matrix.BUILD_PLATFORM}}" /p:NO_CLIENT_ASSETS="1" Server.sln

    - name: Build tools
      run: msbuild /p:Configuration="${{matrix.BUILD_CONFIGURATION}}" /p:Platform="${{matrix.BUILD_PLATFORM}}" /p:NO_CLIENT_ASSETS="1" Tools.sln

    - name: Build client tools
      run: msbuild /p:Configuration="${{matrix.BUILD_CONFIGURATION}}" /p:Platform="${{matrix.BUILD_PLATFORM}}" /p:NO_CLIENT_ASSETS="1" ClientTools.sln

    - name: Build tests
      run: msbuild /p:Configuration="${{matrix.BUILD_CONFIGURATION}}" /p:Platform="${{matrix.BUILD_PLATFORM}}" /p:NO_CLIENT_ASSETS="1" Tests.sln

    - name: Run client tests
      shell: cmd
      working-directory: "bin/${{matrix.BUILD_PLATFORM}}/${{matrix.BUILD_CONFIGURATION}}/client-tests"
      run: |
        xcopy "${{ github.workspace }}\OpenKO-runner-dependencies\${{matrix.BUILD_PLATFORM}}" . /E /I /Y
        client-tests.exe --gtest_print_time=1 --gtest_catch_exceptions=1 --gtest_break_on_failure=0

    - name: Run server tests
      shell: cmd
      working-directory: "bin/${{matrix.BUILD_PLATFORM}}/${{matrix.BUILD_CONFIGURATION}}/server-tests"
      run: |
        xcopy "${{ github.workspace }}\OpenKO-runner-dependencies\${{matrix.BUILD_PLATFORM}}" . /E /I /Y
        server-tests.exe --gtest_print_time=1 --gtest_catch_exceptions=1 --gtest_break_on_failure=0
